# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://ththjang.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ''

# Title of the Site
title: Good day mate!
# Description of the Site
description: A personal website but to share ideas and codes
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: >-
  https://github.com/ththJang/ththJang.github.io/blob/main/assets/images/library_img_libraries.jpg?raw=true

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: jthgreene@gmail.com
facebook_username: jthlol
twitter_username: null
instagram_username: jthgreene
linkedin_username: null
github_username:  ththJang
youtube_channel_id: null
reddit_username: null
behance_username: null
dribbble_username: null
spotify_username: null

# Google Analytics
google-analytics: G-N73ZEVDDM5

# Disqus
disqus-shortname: ththjang-github

# Name of the Author
author-name: Taehwan Jang
# URL for the Image of the Author
author-image: >-
  https://github.com/ththJang/ththJang.github.io/blob/main/assets/images/revised_image2.jpg?raw=true

# 60 Words About the Author
author-about: >-
  Don't get stuck to anything. Glad to talk with you! 

  currently Ph. D. candidate in chemistry at Korea Advanced Institute of Science
  and Technology (KAIST), South Korea.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/ththJang

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-sitemap

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
