markdown: kramdown
url: 'http://ththjang.github.io'
baseurl: null
title: Good day mate!
description: A personal website but to share ideas and codes
site-image: /WhatATheme/assets/images/meta.jpg
site-keywords: 'Site, Template, Theme'
favicon-url: null
heroimage: >-
  https://github.com/ththJang/ththJang.github.io/blob/main/assets/images/library_img_libraries.jpg?raw=true
email: jthgreene@gmail.com
facebook_username: oasis2
twitter_username: null
instagram_username: jthgreene
linkedin_username: null
github_username: ththJang
youtube_channel_id: null
reddit_username: null
behance_username: null
dribbble_username: null
spotify_username: null
google-analytics: null
disqus-shortname: null
author-name: Taehwan Jang
author-image: >-
  https://github.com/ththJang/ththJang.github.io/blob/main/assets/images/revised_image2.jpg?raw=true
author-about: >-
  Don't get stuck to anything. Glad to talk with you! 

  currently Ph. D. candidate in chemistry at Korea Advanced Institute of Science
  and Technology (KAIST), South Korea.
author-url: 'https://github.com/ththJang'
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-sitemap
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
layout: default
comments: true
  provider               : "disqus" # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : ththjang-github # https://hel
